Repository EDCD/EDDI, pull requests merged in 2018-04, with the labels that each got.

#470 #70 use namespaces to distinguish the various types of test
  Tests/BodyScanTests.cs
  Tests/BuildTests.cs
  Tests/CommanderDataTests.cs
  Tests/CommodityTests.cs
  Tests/CoriolisTests.cs
  Tests/DataDefinitionTests.cs
  Tests/DataProviderTests.cs
  Tests/DiffTests.cs
  Tests/EddnTests.cs
  Tests/GeneratorTests.cs
  Tests/JournalMonitorTests.cs
  Tests/PromotionTests.cs
  Tests/ScriptResolverTest.cs
  Tests/ShipTests.cs
  Tests/SpeechTests.cs
  Tests/StarSystemDataTests.cs
  Tests/StatusMonitorTests.cs
  Tests/TranslationTests.cs
  Tests/VersioningTests.cs
  Tests/VoiceAttackPluginTests.cs
Labels: 10. back end enhancement / change (user unaffected)

#471 Demote `Speech failed` to an info level message, as it's not typically something actionable at our level.
  SpeechService/SpeechService.cs
Labels: 10. back end enhancement / change (user unaffected)

#468 Log missing speech scripts at info level, not report
  SpeechResponder/Personality.cs
Labels: 5. priority / painful

#467 Scrub journal timestamps from Rollbar data to improve de-duping.
  Utilities/Logging.cs
Labels: 9. enhancement / change request

#466 Update module data per Rollbar items
  DataDefinitions/ModuleDefinitions.cs
  JournalMonitor/JournalMonitor.cs
  StatusMonitor/StatusMonitor.cs
Labels: 8. inconvenience / annoyance

#475 Corrected 'Location' event handler to use 'station' name instead of '…
  EDDI/EDDI.cs
Labels: 4. show stopper

#469 Amend code where data is not a JSON dictionary
  Utilities/Logging.cs
Labels: 3. crash / lockup

#465 Improve data collection and attempt to resolve rollbar item #10 & 11.
  StatusMonitor/StatusMonitor.cs
Labels: 8. inconvenience / annoyance

#472 Add missing powerplay commodity to commodity definitions.
  DataDefinitions/CommodityDefinitions.cs
Labels: 8. inconvenience / annoyance

#488 Improve rollbar de-duplication
  Utilities/Logging.cs
Labels: 6. bug / not up to spec

#476 Fix sql database write error
  DataProviderService/StarSystemSqLiteRepository.cs
Labels: 6. bug / not up to spec

#477 Correct `tg_shipsystemdata` to `tg_shipsystemsdata`.
  DataDefinitions/Material.cs
Labels: 6. bug / not up to spec

#481 Fix unparseable null values passed from journal reader
  JournalMonitor/JournalMonitor.cs
Labels: 6. bug / not up to spec

#484 Export ship data in `Loadout` format
  EDDI/ChangeLog.md
  ShipMonitor/FrontierApi.cs
  ShipMonitor/ShipMonitor.cs
Labels: 9. enhancement / change request
