Repository EDCD/EDDI, pull requests merged in 2018-02, with the labels that each got.

#324 Feature/eddi single instance
  EDDI/App.xaml
  EDDI/App.xaml.cs
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  EDDI/EDDI.csproj
  EDDI/MainWindow.xaml.cs
  Events/EddiEvents.csproj
  Events/VAInitialized.cs
  ShipMonitor/ShipMonitor.cs
  SpeechResponder/ConfigurationWindow.xaml.cs
  SpeechResponder/eddi.json
  Utilities/Constants.cs
  VoiceAttackResponder/EDDI.vap
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 5. priority / painful

#331 Troubleshooting
  EDDI/MainWindow.xaml
  EDDI/MainWindow.xaml.cs
  README.md
  TROUBLESHOOTING.md
Labels: 8. inconvenience / annoyance

#343 EDSM exception fix
  EDDI/ChangeLog.md
  StarMapService/StarMapService.cs
Labels: 6. bug / not up to spec

#346 Fixes for #345 - out of date scripts and documentation for materials
  EDDI/ChangeLog.md
  SpeechResponder/Variables.md
  SpeechResponder/eddi.json
Labels: 6. bug / not up to spec

#353 Omit the contents of generic web responses from the debug log
  Utilities/Net.cs
Labels: 10. back end enhancement / change (user unaffected)

#366 Disable Galnet monitor by default (for Beyond)
  EDDI/ChangeLog.md
  EDDI/EDDIConfiguration.cs
Labels: 9. enhancement / change request

#369 Combat bond redeemed hotfix (for Beyond)
  EDDI/ChangeLog.md
  JournalMonitor/JournalMonitor.cs
Labels: 6. bug / not up to spec

#368 Update ship state tracking (for Beyond)
  EDDI/ChangeLog.md
  Events/VehicleDestroyedEvent.cs
  JournalMonitor/JournalMonitor.cs
Labels: 9. enhancement / change request

#376 #375 Add 'Under attack' event (for Beyond)
  EDDI/ChangeLog.md
  Events/EddiEvents.csproj
  Events/UnderAttackEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/eddi.json
Labels: 9. enhancement / change request

#385 Fix for #362
  DataDefinitions/ModuleDefinitions.cs
  EDDI/ChangeLog.md
Labels: 9. enhancement / change request
