Repository EDCD/EDDI, pull requests merged in 2018-07, with the labels that each got.

#719 Correct file reference to eddi.it.json
  SpeechResponder/Properties/SpeechResponder.it.resx
Labels: 5. priority / painful

#730 Dramatically reduced CPU utilization in VoiceAtttack
  EDDI/ChangeLog.md
  VoiceAttackResponder/VoiceAttackPlugin.cs
  VoiceAttackResponder/VoiceAttackResponder.cs
Labels: 8. inconvenience / annoyance

#738 Hotfix/735 Swapout check
  DataDefinitions/ModuleDefinitions.cs
  DataDefinitions/Properties/Modules.Designer.cs
  DataDefinitions/Properties/Modules.resx
  JournalMonitor/JournalMonitor.cs
  ShipMonitor/FrontierApi.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
Labels: 6. bug / not up to spec

#749 Update VA standard variables only when they do not match prior state.
  StatusMonitor/StatusMonitor.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 4. show stopper

#742 If we re-obtain a star system from the server, remember it.
  DataProviderService/StarSystemSqLiteRepository.cs
Labels: 6. bug / not up to spec
