Repository EDCD/EDDI, pull requests merged in 2018-03, with the labels that each got.

#394 Fix for #393 - exceptions thrown due to new voice modules in Loadout
  DataDefinitions/ModuleDefinitions.cs
  JournalMonitor/JournalMonitor.cs
Labels: 6. bug / not up to spec

#400 Added the Commander's gender to the Voice Attack variables.
  EDDI/ChangeLog.md
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 9. enhancement / change request

#409 Fix for #407. EDDI will no longer try to sync your full flight log every time it loads
  DataProviderService/StarSystemSqLiteRepository.cs
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  EDSMResponder/ConfigurationWindow.xaml.cs
  EDSMResponder/EDSMResponder.cs
  StarMapService/StarMapService.cs
Labels: 6. bug / not up to spec

#410 Fix for #392 - "Entering" with the 'SRV under ship' event
  EDDI/ChangeLog.md
  Events/EddiEvents.csproj
  Events/SRVUnderShipEvent.cs
  SpeechResponder/eddi.json
  StatusMonitor/StatusMonitor.cs
Labels: 8. inconvenience / annoyance

#419 Shift "instant" fsd status messages to appear only in events and not in the status object.
  StatusMonitor/StatusMonitor.cs
Labels: 8. inconvenience / annoyance

#416 Issue-415: Possible issue in 'Commodity sale check'
  SpeechResponder/eddi.json
Labels: 9. enhancement / change request

#418 Fix for #305. Run actions to update the shipmonitor in the dispatcher thread.
  EDDI/ChangeLog.md
  ShipMonitor/ShipMonitor.cs
Labels: 5. priority / painful

#413 Fix FireGroup typo
  StatusMonitor/StatusMonitor.cs
Labels: 9. enhancement / change request

#433 Update crime definitions for ED 3.0
  DataDefinitions/Crime.cs
  DataDefinitions/Economy.cs
Labels: 9. enhancement / change request

#426 Add jetcone damage event
  EDDI/ChangeLog.md
  Events/EddiEvents.csproj
  Events/JetConeDamageEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/eddi.json
Labels: 9. enhancement / change request

#432 Update materials for ED 3.0
  DataDefinitions/Material.cs
Labels: 9. enhancement / change request

#427 Update commodities for ED 3.0
  DataDefinitions/CommodityDefinitions.cs
Labels: 9. enhancement / change request

#431 Update module definitions for ED 3.0
  DataDefinitions/ModuleDefinitions.cs
Labels: 9. enhancement / change request

#435 Remove duplicates and extra spaces in ModuleDefinitions.cs
  DataDefinitions/ModuleDefinitions.cs
Labels: 6. bug / not up to spec

#436 Initialise the VoiceAttack variable(s) for the Speech Service
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 6. bug / not up to spec

#447 EDDN `Docked` Event - sanity check
  EDDNResponder/EDDNResponder.cs
  Tests/EddnTests.cs
Labels: 6. bug / not up to spec

#441 Revert changes to `Set BodyValues` introduced in commit #c1224107.
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 6. bug / not up to spec

#443 Rename VA plugin status var "srv handbrake" to "srv handbrake activat…
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 8. inconvenience / annoyance

#434 Tidy up the status monitor
  DataDefinitions/Status.cs
  StatusMonitor/StatusMonitor.cs
  Tests/StatusMonitorTests.cs
  Tests/Tests.csproj
Labels: 9. enhancement / change request

#449 Test whether the build successfully generated responder and monitor .dll files.
  EDDI/EDDI.cs
  Tests/BuildTests.cs
  Tests/Tests.csproj
Labels: 10. back end enhancement / change (user unaffected)

#450 Add an overload method to separate out the dependency injection on the EDDNResponder method.
  EDDNResponder/EDDNResponder.cs
Labels: 6. bug / not up to spec
