Repository EDCD/EDDI, pull requests merged in 2018-05, with the labels that each got.

#515 Fix Friends event
  JournalMonitor/JournalMonitor.cs
  Tests/JournalMonitorTests.cs
Labels: 6. bug / not up to spec

#514 Use human readable ship names in events
  EDDI/ChangeLog.md
  Events/CommanderContinuedEvent.cs
  Events/DiedEvent.cs
  ShipMonitor/ModuleArrivedEvent.cs
  ShipMonitor/ModulePurchasedEvent.cs
  ShipMonitor/ModuleRetrievedEvent.cs
  ShipMonitor/ModuleSoldEvent.cs
  ShipMonitor/ModuleSoldFromStorageEvent.cs
  ShipMonitor/ModuleStoredEvent.cs
  ShipMonitor/ModuleSwappedEvent.cs
  ShipMonitor/ModuleTransferEvent.cs
  ShipMonitor/ModulesStored.cs
  ShipMonitor/ShipArrivedEvent.cs
  ShipMonitor/ShipDeliveredEvent.cs
  ShipMonitor/ShipLoadoutEvent.cs
  ShipMonitor/ShipPurchasedEvent.cs
  ShipMonitor/ShipRenamedEvent.cs
  ShipMonitor/ShipSoldEvent.cs
  ShipMonitor/ShipSoldOnRebuyEvent.cs
  ShipMonitor/ShipSwappedEvent.cs
  ShipMonitor/ShipTransferInitiatedEvent.cs
  Tests/ShipTests.cs
Labels: 8. inconvenience / annoyance

#513 Rollbar enhancements
  EDDI/App.config
  EDDI/App.xaml.cs
  EDDI/EDDI.cs
  EDDI/EDDIConfiguration.cs
  EDDI/Properties/Settings.Designer.cs
  EDDI/Properties/Settings.settings
  Utilities/Logging.cs
  Utilities/Utilities.csproj
  Utilities/packages.config
Labels: 10. back end enhancement / change (user unaffected)

#521 Revised and re-enabled "transmit" voice effect.
  EDDI/ChangeLog.md
  SpeechResponder/Help.md
  SpeechResponder/ScriptResolver.cs
  SpeechService/SpeechService.cs
  Tests/SpeechTests.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 9. enhancement / change request

#522 Update Rollbar version checking
  Utilities/Logging.cs
Labels: 6. bug / not up to spec

#519 Implement "safe mode" for mandatory upgrades.
  EDDI/EDDI.cs
  EDDI/MainWindow.xaml.cs
  EDDI/Properties/EddiResources.Designer.cs
  EDDI/Properties/EddiResources.resx
Labels: 3. crash / lockup

#525 Script enhancements
  Events/EddiEvents.csproj
  Events/FineIncurredEvent.cs
  Events/PowerPreparationVoteCastEvent.cs
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.json
Labels: 9. enhancement / change request

#526 Rollbar definition updates
  DataDefinitions/CommodityDefinition.cs
  DataDefinitions/DataScan.cs
  DataDefinitions/Economy.cs
  DataDefinitions/Material.cs
  DataDefinitions/ModuleDefinitions.cs
  DataDefinitions/Properties/Commodities.Designer.cs
  DataDefinitions/Properties/Commodities.resx
  DataDefinitions/Properties/DataScans.Designer.cs
  DataDefinitions/Properties/DataScans.resx
  DataDefinitions/Properties/Economies.resx
  DataDefinitions/Properties/Modules.resx
Labels: 9. enhancement / change request

#527 Add a cooldown between Rollbar reports and tweak data handling
  CompanionAppService/CompanionAppService.cs
  EDDI/EDDIConfiguration.cs
  Utilities/Files.cs
  Utilities/Logging.cs
Labels: 6. bug / not up to spec

#535 Remove incorrect edname "tg_shipsystemdata" from materialmonitor.json. The actual edname is "tg_shipsystemsdata".
  MaterialMonitor/MaterialMonitor.cs
Labels: 6. bug / not up to spec

#542 Fix Cottle null ref. for Volcanism.
  DataDefinitions/Volcanism.cs
Labels: 6. bug / not up to spec

#543 Fixup missing uniqueId for Rollbar data
  EDDI/App.xaml.cs
Labels: 6. bug / not up to spec

#536 Add `Silent running` event
  EDDI/ChangeLog.md
  Events/EddiEvents.csproj
  Events/SilentRunningEvent.cs
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.json
  StatusMonitor/StatusMonitor.cs
Labels: 9. enhancement / change request

#544 Mitigate Rollbar error reporting causing slow startup
  Utilities/Logging.cs
Labels: 6. bug / not up to spec

#548 Add several new unit tests against legacy sql data & disable reporting failed tests to Rollbar
  Tests/App.config
  Tests/CargoMonitorTests.cs
  Tests/CommanderDataTests.cs
  Tests/CommodityTests.cs
  Tests/DataDefinitionTests.cs
  Tests/DataProviderTests.cs
  Tests/EddnTests.cs
  Tests/JournalMonitorTests.cs
  Tests/MaterialMonitorTests.cs
  Tests/PromotionTests.cs
  Tests/ShipTests.cs
  Tests/StarSystemDataTests.cs
  Tests/StatusMonitorTests.cs
  Tests/Tests.csproj
  Tests/packages.config
  Tests/sqlStarSystem1.json
  Tests/sqlStarSystem2.json
  Tests/sqlStarSystem3.json
  Tests/sqlStarSystem4.json
Labels: 10. back end enhancement / change (user unaffected)

#564 Fix for #562 restoring the "Hear it" button in the ship monitor.
  ShipMonitor/ConfigurationWindow.xaml.cs
Labels: 6. bug / not up to spec

#565 Resolve differences between `Body scanned` event properties and `BodyDetails()` properties.
  Events/BodyScannedEvent.cs
  Events/StarScannedEvent.cs
Labels: 8. inconvenience / annoyance

#583 Log unhandled exceptions to the local logs, just in case we aren't able to get the info from Rollbar.
  Utilities/Logging.cs
Labels: 6. bug / not up to spec

#591 If passed a null edName, return null
  DataDefinitions/ModuleDefinitions.cs
Labels: 6. bug / not up to spec

#592 Catch null reference of CommodityQuote with null CommodityDefinition
  EDDNResponder/EDDNResponder.cs
Labels: 6. bug / not up to spec
