Repository EDCD/EDDI, pull requests merged in 2018-08, with the labels that each got.

#775 Update Coriolis URI per Coriolis dev request.
  DataDefinitions/Ship.cs
  EDDI/ChangeLog.md
Labels: 9. enhancement / change request

#782 Fix CurrentStarSystem not matching destination system during `FSD engaged` event
  EDDI/EDDI.cs
Labels: 6. bug / not up to spec

#794 Make system validation more flexible
  EDDI/EDDI.cs
Labels: 6. bug / not up to spec

#779 Add new events for landing gear, cargo scoop, and lights
  EDDI/ChangeLog.md
  ShipMonitor/EddiShipMonitor.csproj
  ShipMonitor/ShipCargoScoopEvent.cs
  ShipMonitor/ShipLandingGearEvent.cs
  ShipMonitor/ShipLightsEvent.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  StatusMonitor/StatusMonitor.cs
Labels: 9. enhancement / change request

#798 Use Economy.FromName rather than Economy.FromEDName for EDDP data
  DataProviderService/DataProviderService.cs
Labels: 5. priority / painful

#800 Fix cargo tracking for 'Commodity sold' and 'Cargo depot' events
  CargoMonitor/CargoMonitor.cs
  DataDefinitions/HaulageAmount.cs
  SpeechResponder/EddiSpeechResponder.csproj
  SpeechResponder/Help.md
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/Variables.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
Labels: 6. bug / not up to spec

#807 Fix economy related exceptions.
  EDDI/EDDI.cs
  EDDPMonitor/EddpMonitor.cs
  Events/JumpedEvent.cs
  Events/LocationEvent.cs
Labels: 6. bug / not up to spec

#806 Prevent error when setting VA version string
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 6. bug / not up to spec

#808 Fix InvalidCastException from conditionallyRefreshProfile()
  CompanionAppService/CompanionAppService.cs
Labels: 6. bug / not up to spec

#811 Add "Guardian" and "Thargoid" superpower definitions
  DataDefinitions/Properties/Superpowers.Designer.cs
  DataDefinitions/Properties/Superpowers.resx
  DataDefinitions/Superpower.cs
  Events/DockedEvent.cs
  Events/JumpedEvent.cs
  Events/LocationEvent.cs
  Tests/JournalMonitorTests.cs
Labels: 8. inconvenience / annoyance

#813 Fix exception that occurs during location events if not docked
  JournalMonitor/JournalMonitor.cs
Labels: 6. bug / not up to spec
