Repository EDCD/EDDI, pull requests merged in 2018-12, with the labels that each got.

#942 Fix test script exceptions
  Events/DockedEvent.cs
  Events/DockingCancelledEvent.cs
  Events/DockingDeniedEvent.cs
  Events/DockingGrantedEvent.cs
  Events/DockingRequestedEvent.cs
  Events/EnteredNormalSpaceEvent.cs
  Events/JumpedEvent.cs
  Events/LocationEvent.cs
  Events/MaterialDiscardedEvent.cs
  Events/MaterialDonatedEvent.cs
  Events/ModificationCraftedEvent.cs
  Events/ScreenshotEvent.cs
  Events/SearchAndRescueEvent.cs
  Events/SettlementApproachedEvent.cs
  Events/UndockedEvent.cs
  JournalMonitor/JournalMonitor.cs
  MissionMonitor/MissionAcceptedEvent.cs
  ShipMonitor/ModulePurchasedEvent.cs
  ShipMonitor/ModuleRetrievedEvent.cs
  ShipMonitor/ModuleSoldEvent.cs
  ShipMonitor/ModuleStoredEvent.cs
  ShipMonitor/ModuleSwappedEvent.cs
  ShipMonitor/ModulesStored.cs
  ShipMonitor/ShipLoadoutEvent.cs
  ShipMonitor/ShipPurchasedEvent.cs
  ShipMonitor/ShipSoldEvent.cs
  ShipMonitor/ShipSwappedEvent.cs
  ShipMonitor/ShipTransferInitiatedEvent.cs
Labels: 6. bug / not up to spec

#944 Extract local data prior to StarSystem recovery
  DataProviderService/StarSystemSqLiteRepository.cs
  EDDI/ChangeLog.md
Labels: 6. bug / not up to spec

#945 Update material rarities
  DataDefinitions/Material.cs
  EDDI/ChangeLog.md
Labels: 8. inconvenience / annoyance

#951 EDSM station data: Fix null reference exception from missing faction info
  StarMapService/EdsmStationData.cs
Labels: 6. bug / not up to spec

#953 Clarify that verbose logs are only placed on the desktop when the `Report an Issue` button is clicked.
  EDDI/Properties/MainWindow.Designer.cs
  EDDI/Properties/MainWindow.resx
Labels: 8. inconvenience / annoyance

#932 Replace MaterialLocations.json with a translatable resx file (compared against Inara for accuracy).
  DataDefinitions/EddiDataDefinitions.csproj
  DataDefinitions/Material.cs
  DataDefinitions/Properties/MaterialLocations.Designer.cs
  DataDefinitions/Properties/MaterialLocations.resx
  EDDI/ChangeLog.md
  MaterialMonitor/MaterialMonitor.cs
Labels: 9. enhancement / change request, low priority

#974 Convert station model pronunciation fixups to use `P()` function, rather than editing the invariant name.
  DataDefinitions/Properties/StationModels.Designer.cs
  DataDefinitions/Properties/StationModels.resx
  EDDI/ChangeLog.md
  SpeechResponder/ScriptResolver.cs
  SpeechService/Translations.cs
  Tests/EdsmDataTests.cs
  Tests/TranslationTests.cs
Labels: 6. bug / not up to spec

#982 Added new ship and module defs (incomplete)
  DataDefinitions/ModuleDefinitions.cs
  DataDefinitions/Properties/Modules.Designer.cs
  DataDefinitions/Properties/Modules.de.resx
  DataDefinitions/Properties/Modules.es.resx
  DataDefinitions/Properties/Modules.fr.resx
  DataDefinitions/Properties/Modules.resx
  DataDefinitions/ShipDefinitions.cs
Labels: 9. enhancement / change request, chapter 4

#984 Fix Blueprint Names in `EngineerCraft` event
  JournalMonitor/JournalMonitor.cs
Labels: 6. bug / not up to spec

#983 Restore station model translations and fix #981.
  DataDefinitions/Properties/StationModels.de.resx
  DataDefinitions/Properties/StationModels.es.resx
  DataDefinitions/Properties/StationModels.fr.resx
  DataDefinitions/Properties/StationModels.it.resx
Labels: 6. bug / not up to spec

#986 Add a new `VoiceDetails` function to Cottle
  EDDI/ChangeLog.md
  SpeechResponder/EddiSpeechResponder.csproj
  SpeechResponder/Help.md
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/Variables.md
  SpeechService/SpeechService.cs
Labels: 9. enhancement / change request

#995 Fix the message received event for v. 3.3 (again)
  EDDI/ChangeLog.md
  Events/MessageReceivedEvent.cs
  JournalMonitor/JournalMonitor.cs
  Tests/JournalMonitorTests.cs
Labels: 6. bug / not up to spec

#1006 Various definition tidy ups. See commit details.
  EDDI/EDDIConfiguration.cs
  EDDI/MainWindow.xaml.cs
  Events/BodyScannedEvent.cs
  JournalMonitor/JournalMonitor.cs
  StarMapService/EdsmBodyData.cs
  StarMapService/EdsmFactionData.cs
  StarMapService/EdsmSystemData.cs
  StatusMonitor/StatusMonitor.cs
Labels: 6. bug / not up to spec

#1010 A few more definition updates
  DataDefinitions/CommodityDefinition.cs
  DataDefinitions/ModuleDefinitions.cs
  DataDefinitions/Properties/Commodities.Designer.cs
  DataDefinitions/Properties/Commodities.resx
  DataDefinitions/Properties/Modules.Designer.cs
  DataDefinitions/Properties/Modules.resx
  DataDefinitions/Properties/StationModels.Designer.cs
  DataDefinitions/Properties/StationModels.resx
  DataDefinitions/StationModel.cs
  DataProviderService/LegacyEddpService.cs
  JournalMonitor/JournalMonitor.cs
Labels: 9. enhancement / change request

#1011 Update scripts
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
Labels: 9. enhancement / change request

#1012 Disable CAPI until we're ready to do something with it.
  EDDI/EDDI.cs
Labels: 9. enhancement / change request

#1020 If server StarSystem data is not available, use stale local data
  DataProviderService/StarSystemSqLiteRepository.cs
Labels: 6. bug / not up to spec

#1021 EDDN responder updates
  EDDI/ChangeLog.md
  EDDNResponder/EDDNResponder.cs
  Tests/EddnTests.cs
Labels: 5. priority / painful

#1025 Fix `Friends status` event test script not firing.
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  JournalMonitor/JournalMonitor.cs
Labels: 7. confusing

#1026 Use case insensitive sql searches for searching our star systems database
  DataProviderService/StarSystemSqLiteRepository.cs
  EDDI/EDDI.cs
  EDDI/MainWindow.xaml.cs
Labels: 8. inconvenience / annoyance, PR submitted

#1031 Revisions to prevent inaccurate star position data being reported to EDDN
  EDDI/ChangeLog.md
  EDDNResponder/EDDNResponder.cs
  EDDNResponder/EddiEddnResponder.csproj
  EDDNResponder/Properties/EddnResources.Designer.cs
  EDDNResponder/Properties/EddnResources.resx
  Tests/EddnTests.cs
Labels: 4. show stopper
