Repository EDCD/EDDI, pull requests merged in 2018-06, with the labels that each got.

#617 Fixed Zirconium rarity
  DataDefinitions/Material.cs
Labels: 8. inconvenience / annoyance

#619 VoiceAttack NullReference exceptions - system state
  DataDefinitions/StarSystem.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 6. bug / not up to spec, please test

#605 Fix `System report` missing after `FSD engaged` event
  CargoMonitor/CargoMonitor.cs
  CompanionAppService/CompanionAppService.cs
  DataDefinitions/StarSystem.cs
  DataDefinitions/Status.cs
  DataProviderService/DataProviderService.cs
  DataProviderService/StarSystemSqLiteRepository.cs
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  EDDNResponder/EDDNResponder.cs
  EDDPMonitor/EddpMonitor.cs
  EDDPMonitor/SystemFactionChangedEvent.cs
  EDDPMonitor/SystemStateChangedEvent.cs
  Events/MarketInformationUpdatedEvent.cs
  Events/NPCAttackCommencedEvent.cs
  Events/NPCCargoScanCommencedEvent.cs
  Events/NPCInterdictionCommendedEvent.cs
  Events/SRVTurretDeployableEvent.cs
  Events/StationNoFireZoneEnteredEvent.cs
  Events/StationNoFireZoneExitedEvent.cs
  GalnetMonitor/GalnetMonitor.cs
  GalnetMonitor/GalnetNewsPublishedEvent.cs
  JournalMonitor/JournalMonitor.cs
  MaterialMonitor/MaterialMonitor.cs
  MaterialMonitor/MaterialThresholdEvent.cs
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/Variables.md
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.json
  Tests/CargoMonitorTests.cs
  Tests/ShipTests.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 6. bug / not up to spec

#611 Corrosion Resistant Cargo Racks & ship cargocapacity
  ShipMonitor/FrontierApi.cs
  ShipMonitor/ShipMonitor.cs
Labels: 6. bug / not up to spec

#609 Use edname "Drones" rather than localizedName "Limpets" for `Limpet check` script.
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.json
Labels: 6. bug / not up to spec

#612 Revise data directory scrubber to scrub both messages and data and prevent data directories from leaking through in Rollbar reports.
  Utilities/Logging.cs
Labels: 6. bug / not up to spec

#615 Gracefully handle `CurrentStarSystem` being null.
  EDDI/EDDI.cs
Labels: 6. bug / not up to spec

#616 Fixed Docked event `allegiance` variable not being accessible to Cottle users.
  Events/DockedEvent.cs
Labels: 8. inconvenience / annoyance

#607 Market information & ship role fixes
  DataDefinitions/Ship.cs
  EDDI/ChangeLog.md
  SpeechResponder/Help.md
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.json
Labels: 6. bug / not up to spec

#625 Refactored, values updating split into distinct threads for events and bg values.
  VoiceAttackResponder/EddiVoiceAttackResponder.csproj
  VoiceAttackResponder/VoiceAttackPlugin.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 10. back end enhancement / change (user unaffected)

#631 Hotfix/623 market reports
  Events/MissionCompletedEvent.cs
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
Labels: 6. bug / not up to spec

#646 Various bugfixes from Rollbar data (see commit details)
  DataDefinitions/CommodityDefinition.cs
  DataDefinitions/Properties/Commodities.Designer.cs
  DataDefinitions/Properties/Commodities.de.resx
  DataDefinitions/Properties/Commodities.es.resx
  DataDefinitions/Properties/Commodities.fr.resx
  DataDefinitions/Properties/Commodities.hu.resx
  DataDefinitions/Properties/Commodities.resx
  DataDefinitions/StarSystem.cs
  DataDefinitions/SystemState.cs
  DataProviderService/DataProviderService.cs
  EDDI/App.xaml.cs
  EDDPMonitor/SystemStateChangedEvent.cs
  ShipMonitor/ShipMonitor.cs
  Tests/DataDefinitionTests.cs
  Utilities/Logging.cs
  Utilities/Versioning.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 6. bug / not up to spec

#647 Material monitor collection synchronization
  MaterialMonitor/MaterialMonitor.cs
  VoiceAttackResponder/EddiVoiceAttackResponder.csproj
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 6. bug / not up to spec

#713 Feature/chapter 2 items
  CargoMonitor/CargoMonitor.cs
  DataDefinitions/CommodityDefinition.cs
  DataDefinitions/EddiDataDefinitions.csproj
  DataDefinitions/Material.cs
  DataDefinitions/ModuleDefinitions.cs
  DataDefinitions/Properties/Commodities.Designer.cs
  DataDefinitions/Properties/Commodities.de.resx
  DataDefinitions/Properties/Commodities.es.resx
  DataDefinitions/Properties/Commodities.fr.resx
  DataDefinitions/Properties/Commodities.hu.resx
  DataDefinitions/Properties/Commodities.resx
  DataDefinitions/ShipDefinitions.cs
  Tests/CargoMonitorTests.cs
Labels: 9. enhancement / change request
