Repository EDCD/EDDI, pull requests merged in 2019-02, with the labels that each got.

#1142 Utilize a shared / common instance for the EDSM responder.
  EDDI/EDDI.cs
  EDSMResponder/EDSMResponder.cs
Labels: 10. back end enhancement / change (user unaffected)

#1152 Hotfix - Cargo change detection
  CargoMonitor/CargoMonitor.cs
  Tests/CargoMonitorTests.cs
Labels: 6. bug / not up to spec

#1147 Add event handler for FSDTarget event
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  Events/EddiEvents.csproj
  Events/FSDTargetEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/SpeechResponder.cs
  SpeechResponder/Variables.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.ja.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.ru.json
  VoiceAttackResponder/VoiceAttackVariables.cs
  docs/VoiceAttack-Integration.md
Labels: 9. enhancement / change request

#1154 Fix system visit counts reseting
  DataProviderService/StarSystemSqLiteRepository.cs
  EDDI/EDDI.cs
Labels: 8. inconvenience / annoyance

#1150 Improve thread safety around the keepAlive method.
  EDDI/EDDI.cs
  Tests/BuildTests.cs
  Tests/EddiCoreTests.cs
  Tests/JournalMonitorTests.cs
  Tests/Tests.csproj
Labels: 5. priority / painful

#1164 Tighten up EDSM credentials management
  EDDI/EDDI.cs
  EDSMResponder/ConfigurationWindow.xaml.cs
  EDSMResponder/EDSMResponder.cs
  StarMapService/StarMapService.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 8. inconvenience / annoyance

#1167 Add parameters to control whether ships are written to permanent storage during ship tests
  ShipMonitor/ShipMonitor.cs
  Tests/ShipTests.cs
Labels: 10. back end enhancement / change (user unaffected)

#1172 Add `Instance` properties to all monitors
  CargoMonitor/CargoMonitor.cs
  CargoMonitor/ConfigurationWindow.xaml.cs
  DataDefinitions/Body.cs
  DataDefinitions/StarSystem.cs
  DataDefinitions/Station.cs
  DataDefinitions/Status.cs
  DataProviderService/StarSystemSqLiteRepository.cs
  EDDI/EDDI.cs
  EDDPMonitor/EddpMonitor.cs
  Events/EddiEvents.csproj
  Events/StatusEvent.cs
  GalnetMonitor/ConfigurationWindow.xaml.cs
  GalnetMonitor/GalnetMonitor.cs
  JournalMonitor/JournalMonitor.cs
  MaterialMonitor/ConfigurationWindow.xaml.cs
  MaterialMonitor/MaterialMonitor.cs
  MissionMonitor/ConfigurationWindow.xaml.cs
  MissionMonitor/MissionMonitor.cs
  ShipMonitor/ConfigurationWindow.xaml.cs
  ShipMonitor/ShipMonitor.cs
  SpeechResponder/ConfigurationWindow.xaml.cs
  SpeechResponder/EditScriptWindow.xaml.cs
  SpeechResponder/Personality.cs
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/SpeechResponder.cs
  StatusMonitor/StatusMonitor.cs
  Tests/StatusMonitorTests.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
  VoiceAttackResponder/VoiceAttackResponder.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 9. enhancement / change request

#1176 Fix VA variables (partially reverts PR #1172)
  CargoMonitor/CargoMonitor.cs
  CargoMonitor/ConfigurationWindow.xaml.cs
  EDDI/EDDI.cs
  EDDPMonitor/EddpMonitor.cs
  GalnetMonitor/ConfigurationWindow.xaml.cs
  GalnetMonitor/GalnetMonitor.cs
  JournalMonitor/JournalMonitor.cs
  MaterialMonitor/ConfigurationWindow.xaml.cs
  MaterialMonitor/MaterialMonitor.cs
  MissionMonitor/ConfigurationWindow.xaml.cs
  MissionMonitor/MissionMonitor.cs
  ShipMonitor/ConfigurationWindow.xaml.cs
  ShipMonitor/ShipMonitor.cs
  SpeechResponder/ConfigurationWindow.xaml.cs
  SpeechResponder/EditScriptWindow.xaml.cs
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/SpeechResponder.cs
  SpeechService/SpeechService.cs
  StatusMonitor/StatusMonitor.cs
  Tests/StatusMonitorTests.cs
  VoiceAttackResponder/EDDI.vap
  VoiceAttackResponder/VoiceAttackPlugin.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 6. bug / not up to spec

#1189 VoiceAttack event handling reworked to minimize delays
  EDDI/ChangeLog.md
  ShipMonitor/ConfigurationWindow.xaml.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
  VoiceAttackResponder/VoiceAttackResponder.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
  docs/VoiceAttack-Integration.md
Labels: 6. bug / not up to spec

#1196 Restore legacy VA home system and home station variables.
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 7. confusing

#1202 Speech responder priorities
  CompanionAppService/CompanionAppService.cs
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  EDDI/MainWindow.xaml.cs
  Events/Event.cs
  ShipMonitor/ConfigurationWindow.xaml.cs
  SpeechResponder/ConfigurationWindow.xaml
  SpeechResponder/ConfigurationWindow.xaml.cs
  SpeechResponder/EddiSpeechResponder.csproj
  SpeechResponder/EditScriptWindow.xaml.cs
  SpeechResponder/MarkdownWindow.xaml
  SpeechResponder/MarkdownWindow.xaml.cs
  SpeechResponder/Properties/SpeechResponder.Designer.cs
  SpeechResponder/Properties/SpeechResponder.de.resx
  SpeechResponder/Properties/SpeechResponder.es.resx
  SpeechResponder/Properties/SpeechResponder.fr.resx
  SpeechResponder/Properties/SpeechResponder.hu.resx
  SpeechResponder/Properties/SpeechResponder.ja.resx
  SpeechResponder/Properties/SpeechResponder.resx
  SpeechResponder/Script.cs
  SpeechResponder/SpeechResponder.cs
  SpeechResponder/SpeechResponderHelp.md
  SpeechService/EddiSpeech.cs
  SpeechService/EddiSpeechService.csproj
  SpeechService/SpeechService.cs
  Tests/SpeechUnitTests.cs
  Tests/Tests.csproj
  VoiceAttackResponder/VoiceAttackPlugin.cs
  docs/VoiceAttack-Integration.md
Labels: 9. enhancement / change request

#1203 Fix erroneous edname being reported to EDDN
  DataDefinitions/ModuleDefinitions.cs
Labels: 6. bug / not up to spec

#1204 Correct VoiceAttack description text to match VoiceAttack's redesigned UI
  VoiceAttackResponder/Properties/VoiceAttack.Designer.cs
  VoiceAttackResponder/Properties/VoiceAttack.resx
Labels: 9. enhancement / change request

#1206 Prevent unit tests from writing to permanent storage
  ShipMonitor/ShipMonitor.cs
  Tests/BodyScanTests.cs
  Tests/CargoMonitorTests.cs
  Tests/CommanderDataTests.cs
  Tests/CommodityTests.cs
  Tests/CoriolisTests.cs
  Tests/DataDefinitionTests.cs
  Tests/DataProviderTests.cs
  Tests/DiffTests.cs
  Tests/EddiCoreTests.cs
  Tests/EddnTests.cs
  Tests/EdsmDataTests.cs
  Tests/JournalMonitorTests.cs
  Tests/MaterialMonitorTests.cs
  Tests/MissionMonitorTests.cs
  Tests/PromotionTests.cs
  Tests/ScriptResolverTest.cs
  Tests/ShipTests.cs
  Tests/SpeechTests.cs
  Tests/StatusMonitorTests.cs
  Tests/TestBase.cs
  Tests/Tests.csproj
  Tests/TranslationTests.cs
  Tests/VersioningTests.cs
  Tests/VoiceAttackPluginTests.cs
  Utilities/Files.cs
Labels: 10. back end enhancement / change (user unaffected)
