Repository EDCD/EDDI, pull requests merged in 2019-09, with the labels that each got.

#1468 Fix inadvertantly disabled hyperlink in the Speech Responder tab
  SpeechResponder/ConfigurationWindow.xaml.cs
Labels: 6. bug / not up to spec

#1471 Process multiple commodity changes in Cargo 'update' events
  CargoMonitor/CargoMonitor.cs
Labels: 6. bug / not up to spec

#1477 Revise the `Delete` button in the Speech Responder UI to either `Delete` or `Reset`, as appropriate.
  SpeechResponder/ConfigurationWindow.xaml
  SpeechResponder/ConfigurationWindow.xaml.cs
  SpeechResponder/EditScriptWindow.xaml
  SpeechResponder/EditScriptWindow.xaml.cs
  SpeechResponder/Personality.cs
  SpeechResponder/Properties/SpeechResponder.Designer.cs
  SpeechResponder/Properties/SpeechResponder.resx
  SpeechResponder/Script.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
Labels: 7. confusing

#1494 Fixup ambiguous wpf references
  EDDPMonitor/ConfigurationWindow.xaml.cs
  SpeechResponder/ConfigurationWindow.xaml
  SpeechResponder/ConfigurationWindow.xaml.cs
Labels: 10. back end enhancement / change (user unaffected)

#1499 Correct pronunciation of "Luyten 205-128" to speak the dash
  SpeechService/Translations.cs
Labels: 8. inconvenience / annoyance

#1495 Hotfix/missing independent rep
  InaraResponder/InaraResponder.cs
  JournalMonitor/JournalMonitor.cs
  Tests/JournalMonitorTests.cs
Labels: 6. bug / not up to spec

#1501 Preserve exploration results through server updates
  DataDefinitions/StarSystem.cs
  DataProviderService/StarSystemSqLiteRepository.cs
  EDDI/EDDI.cs
Labels: 8. inconvenience / annoyance

#1503 Revise architecture: InaraService
  EDDI/EDDI.cs
  EDDI/Eddi.csproj
  EddiInaraService/EddiInaraService.csproj
  EddiInaraService/InaraAPICmdrProfile.cs
  EddiInaraService/InaraAPIEvent.cs
  EddiInaraService/InaraCmdr.cs
  EddiInaraService/InaraService.cs
  InaraResponder/InaraResponder.cs
  SpeechResponder/ScriptResolver.cs
  Tests/TestBase.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 10. back end enhancement / change (user unaffected)

#1505 3.5 Feature - `Ship targeted' event 'power` property.
  CrimeMonitor/CrimeMonitor.cs
  Events/ShipTargetedEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/eddi.json
Labels: 9. enhancement / change request

#1504 3.5 Feature - 'FSDTarget' event 'remainingjumpsinroute' property
  Events/FSDTargetEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/eddi.json
Labels: 9. enhancement / change request

#1506 3.5 Feature - New status properties
  SpeechResponder/Variables.md
  StatusMonitor/Status.cs
  StatusMonitor/StatusMonitor.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 9. enhancement / change request

#1509 3.5 Feature - Surface signals and ring hotspots
  DataDefinitions/EddiDataDefinitions.csproj
  DataDefinitions/Properties/SignalSource.Designer.cs
  DataDefinitions/Properties/SignalSource.resx
  DataDefinitions/SignalAmount.cs
  DataDefinitions/SignalSource.cs
  Events/EddiEvents.csproj
  Events/RingHotspotsEvent.cs
  Events/SurfaceSignalsEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
Labels: 9. enhancement / change request

#1511 Fix repeating powerplay event
  EDDI/EDDI.cs
  EDDI/EDDIConfiguration.cs
Labels: 6. bug / not up to spec

#1510 3.5 Feature - Nearest destination for `Liftoff` and `Touchdown`…
  Events/LiftoffEvent.cs
  Events/TouchdownEvent.cs
  JournalMonitor/JournalMonitor.cs
Labels: 9. enhancement / change request

#1507 3.5 Feature - Scan events system data
  EDDI/EDDI.cs
  Events/BodyMappedEvent.cs
  Events/RingMappedEvent.cs
  JournalMonitor/JournalMonitor.cs
Labels: 9. enhancement / change request

#1512 Preserve language settings across both standalone and VoiceAtta…
  EDDI/App.xaml.cs
  EDDI/EDDIConfiguration.cs
  EDDI/MainWindow.xaml.cs
  EDDI/Properties/MainWindow.Designer.cs
  EDDI/Properties/MainWindow.resx
Labels: 6. bug / not up to spec

#1538 Polish up `nearestdestination` for touchdown, takeoff, and appr…
  DataDefinitions/Properties/SignalSource.Designer.cs
  DataDefinitions/Properties/SignalSource.pt-BR.resx
  DataDefinitions/Properties/SignalSource.resx
  DataDefinitions/SignalSource.cs
  Events/LiftoffEvent.cs
  Events/SettlementApproachedEvent.cs
  Events/TouchdownEvent.cs
  JournalMonitor/JournalMonitor.cs
  Tests/JournalMonitorTests.cs
Labels: 6. bug / not up to spec

#1527 Fix body.shortname
  Events/BodyMappedEvent.cs
  Events/BodyScannedEvent.cs
  JournalMonitor/JournalMonitor.cs
Labels: 6. bug / not up to spec

#1531 Make body & star scanned 'scantype` property user-facing
  Events/BodyScannedEvent.cs
  Events/StarScannedEvent.cs
Labels: 8. inconvenience / annoyance

#1536 Update additional station properties when requesting docking and docking
  EDDI/EDDI.cs
Labels: 10. back end enhancement / change (user unaffected)

#1534 Add a wpf multibinding to ensure that the default personality is not rendered editable.
  SpeechResponder/ConfigurationWindow.xaml
  SpeechResponder/ConfigurationWindow.xaml.cs
  SpeechResponder/Personality.cs
Labels: 6. bug / not up to spec
