Repository EDCD/EDDI, pull requests merged in 2019-01, with the labels that each got.

#1058 Add translations for commodity `UnknownBiologicalMatter`
  DataDefinitions/Properties/Commodities.Designer.cs
  DataDefinitions/Properties/Commodities.de.resx
  DataDefinitions/Properties/Commodities.es.resx
  DataDefinitions/Properties/Commodities.fr.resx
  DataDefinitions/Properties/Commodities.resx
Labels: 9. enhancement / change request

#1060 Update the `Docking denied` test event to resolve an exception
  Events/DockingDeniedEvent.cs
Labels: 6. bug / not up to spec

#1063 Use event data to synthesize a basic main star when jumping into unexplored systems
  EDDI/EDDI.cs
Labels: 8. inconvenience / annoyance

#1066 Fix body system metadata sometimes being not set.
  DataProviderService/DataProviderService.cs
  EDDI/EDDI.cs
Labels: 8. inconvenience / annoyance

#1091 Incorporate Galnet regex tweak
  GalnetMonitor/Properties/GalnetMonitor.Designer.cs
  GalnetMonitor/Properties/GalnetMonitor.resx
Labels: 9. enhancement / change request

#1092 Move promotion related rewards from the `Mission completed` script to the promotion scripts
  EDDI/ChangeLog.md
  Events/EmpirePromotionEvent.cs
  Events/FederationPromotionEvent.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
Labels: 6. bug / not up to spec

#1111 Fix EDDI hanging when trying to input home system
  EDDI/EDDI.cs
Labels: 6. bug / not up to spec

#1113 Honor disabled plugin settings
  EDDI/PluginSkeleton.xaml.cs
  SpeechResponder/SpeechResponder.cs
Labels: 8. inconvenience / annoyance

#1114 Don't assume that ship.maxfuel is set. It may be null.
  ShipMonitor/ShipMonitor.cs
Labels: 6. bug / not up to spec

#1117 Fix invalid cast exceptions in the EDSM responder
  EDSMResponder/EDSMResponder.cs
Labels: 6. bug / not up to spec

#1119 Improve handling of module events when shipyard contains minimal or no ship definition.
  ShipMonitor/ModulePurchasedEvent.cs
  ShipMonitor/ModuleRetrievedEvent.cs
  ShipMonitor/ModuleSoldEvent.cs
  ShipMonitor/ModuleStoredEvent.cs
  ShipMonitor/ModulesStored.cs
  ShipMonitor/ShipMonitor.cs
  Tests/ShipTests.cs
Labels: 6. bug / not up to spec

#1125 Better Message Recieved script
  EDDI/ChangeLog.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
Labels: 9. enhancement / change request

#1126 Fix systems not being saved to the database correctly
  DataProviderService/DataProviderService.cs
  DataProviderService/StarSystemSqLiteRepository.cs
  EDSMResponder/ConfigurationWindow.xaml.cs
  EDSMResponder/EDSMResponder.cs
Labels: 5. priority / painful

#1140 Enforce first in first out (FIFO) ordering for event processing.
  CargoMonitor/CargoMonitor.cs
  CompanionAppService/CompanionAppService.cs
  EDDI/EDDI.cs
  EDDNResponder/EDDNResponder.cs
  EDDPMonitor/EddpMonitor.cs
  GalnetMonitor/GalnetMonitor.cs
  JournalMonitor/JournalMonitor.cs
  MaterialMonitor/MaterialMonitor.cs
  MissionMonitor/MissionMonitor.cs
  SpeechResponder/SpeechResponder.cs
  StatusMonitor/StatusMonitor.cs
  Tests/CargoMonitorTests.cs
  Tests/EddnTests.cs
  Tests/MissionMonitorTests.cs
  Tests/ShipTests.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 6. bug / not up to spec
