Repository EDCD/EDDI, pull requests merged in 2019-06, with the labels that each got.

#1329 Fix localized chromaticity
  DataDefinitions/StarClass.cs
  EDDI/ChangeLog.md
Labels: 6. bug / not up to spec

#1333 Add definition for Advanced Multi-Cannon
  DataDefinitions/ModuleDefinitions.cs
  DataDefinitions/Properties/Modules.Designer.cs
  DataDefinitions/Properties/Modules.de.resx
  DataDefinitions/Properties/Modules.es.resx
  DataDefinitions/Properties/Modules.fr.resx
  DataDefinitions/Properties/Modules.hu.resx
  DataDefinitions/Properties/Modules.pt-BR.resx
  DataDefinitions/Properties/Modules.resx
  DataDefinitions/Properties/Modules.ru.resx
Labels: 8. inconvenience / annoyance

#1334 Fix `Star report` null probabilities
  EDDI/ChangeLog.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.ru.json
Labels: 8. inconvenience / annoyance

#1337 Null probabilities were being treated as high probabilities, a check to make sure that `reportbody` wasn't null was missing.
  EDDI/ChangeLog.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
Labels: 8. inconvenience / annoyance

#1335 Revise `System scan complete` script to reduce verbosity and increase variety
  EDDI/ChangeLog.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
Labels: 8. inconvenience / annoyance

#1360 Add a few additional events to our unhandled events list.
  JournalMonitor/JournalMonitor.cs
Labels: 10. back end enhancement / change (user unaffected)

#1348 Fix french scripts accentuated characters
  EDDI/ChangeLog.md
  SpeechResponder/eddi.fr.json
Labels: 6. bug / not up to spec

#1354 Destination Data Clearing Hotfix
  MissionMonitor/MissionMonitor.cs
  SpeechResponder/eddi.json
Labels: 6. bug / not up to spec

#1356 Fix EDDN commodies message exception due to EDDNEconomy definition.
  EDDNResponder/EDDNEconomy.cs
Labels: 6. bug / not up to spec

#1355 Fix exception that can occur when `happiness` or `updated_at` properties are not provided for faction BGS data
  BgsService/BgsFactionData.cs
Labels: 6. bug / not up to spec

#1347 Fix EDDN exception - shipyard information
  DataDefinitions/Ship.cs
  EDDNResponder/EDDNResponder.cs
  ShipMonitor/ShipLoadoutEvent.cs
  ShipMonitor/ShipMonitor.cs
  Tests/ShipTests.cs
  Utilities/JsonParsing.cs
Labels: 6. bug / not up to spec

#1365 Debug logs - write current culture and increase truncated log length
  EDDI/MainWindow.xaml.cs
Labels: 10. back end enhancement / change (user unaffected)

#1366 Fix exception when sorting modules after module purchase
  ShipMonitor/ShipMonitor.cs
Labels: 6. bug / not up to spec

#1352 Handle redundant economies
  DataDefinitions/Station.cs
  DataProviderService/LegacyEddpService.cs
  StarMapService/EdsmStationData.cs
  Tests/JournalMonitorTests.cs
Labels: 8. inconvenience / annoyance

#1374 Add `Ring mapped` event and resolve `develop` bugs related to probing rings
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  Events/EddiEvents.csproj
  Events/RingMappedEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.ja.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
  Tests/EddiCoreTests.cs
Labels: 6. bug / not up to spec
