Repository EDCD/EDDI, pull requests merged in 2019-07, with the labels that each got.

#1396 Fix BGS Faction invalid cast exception
  BgsService/BgsFactionData.cs
  EDDI/ChangeLog.md
Labels: 3. crash / lockup

#1383 Correct `Bodies mapped` script
  EDDI/ChangeLog.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
Labels: 6. bug / not up to spec

#1390 Fix EDDI crashes on startup for non-English Windows installations.
  EDDI/ChangeLog.md
  EDDI/MainWindow.xaml.cs
Labels: 3. crash / lockup

#1397 Clarify when `nextsystem` information is transferred to `system`.
  SpeechResponder/Variables.md
Labels: 8. inconvenience / annoyance

#1401 Resolve Frontier 'bug' causing multiple triggers of 'System scan complete' event
  DataDefinitions/StarSystem.cs
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  Tests/EddiCoreTests.cs
Labels: 8. inconvenience / annoyance

#1402 Update `Docking granted` script to include basic landing pad info for surface ports.
  EDDI/ChangeLog.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.ru.json
Labels: 9. enhancement / change request

#1404 Code coverage
  .codecov.yml
  EDDI.sln
  Installer.iss
  Tests/BgsDataTests.cs
  Tests/CapiShipyardTests.cs
  Tests/DataDefinitionTests.cs
  Tests/DataProviderTests.cs
  Tests/EdsmDataTests.cs
  Tests/OAuthClientIDTests.cs
  Tests/Properties/Abasheli Barracks.json
  Tests/Properties/Resources.Designer.cs
  Tests/Properties/Resources.resx
  Tests/Properties/bgsFaction.json
  Tests/Properties/edsmBodies.json
  Tests/Properties/edsmDeaths.json
  Tests/Properties/edsmFactions.json
  Tests/Properties/edsmStations.json
  Tests/Properties/edsmSystem.json
  Tests/Properties/edsmTraffic.json
  Tests/Properties/fighterLoadout.json
  Tests/Properties/loadout.json
  Tests/Properties/shipMonitor.json
  Tests/Properties/sqlStarSystem1.json
  Tests/Properties/sqlStarSystem2.json
  Tests/Properties/sqlStarSystem3.json
  Tests/Properties/sqlStarSystem4.json
  Tests/Properties/starsystems.txt
  Tests/Properties/vehicle.json
  Tests/ShipTests.cs
  Tests/TestBase.cs
  Tests/Tests.csproj
  Tests/VoiceAttackPluginTests.cs
  Tests/packages.config
  appveyor.yml
Labels: 10. back end enhancement / change (user unaffected)

#1409 Code coverage fixes
  .codecov.yml
  Tests/packages.config
  appveyor.yml
Labels: 5. priority / painful

#1415 Code coverage tweaks
  appveyor.yml
Labels: 9. enhancement / change request

#1411 Remove rounding from the "full" bool in the `Ship refuelled` event.
  JournalMonitor/JournalMonitor.cs
  Tests/ShipTests.cs
Labels: 6. bug / not up to spec

#1413 Fix spurious "Information:" after jumping due to non-empty `System state report`.
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.ru.json
Labels: 8. inconvenience / annoyance

#1421 Fix 1420
  EDDI/MainWindow.xaml.cs
Labels: 4. show stopper

#1414 Humanise() tweaks
  SpeechService/Properties/Phrases.Designer.cs
  SpeechService/Properties/Phrases.de.resx
  SpeechService/Properties/Phrases.es.resx
  SpeechService/Properties/Phrases.fr.resx
  SpeechService/Properties/Phrases.hu.resx
  SpeechService/Properties/Phrases.it.resx
  SpeechService/Properties/Phrases.pt-BR.resx
  SpeechService/Properties/Phrases.resx
  SpeechService/Properties/Phrases.ru.resx
  SpeechService/Translations.cs
  Tests/SpeechUnitTests.cs
Labels: 9. enhancement / change request

#1423 Remove the StationLargestPad `FromSize` method.
  CrimeMonitor/CrimeMonitor.cs
  DataDefinitions/Properties/StationLargestPad.Designer.cs
  DataDefinitions/Ship.cs
  DataDefinitions/Station.cs
  DataDefinitions/StationLargestPad.cs
  NavigationService/Navigation.cs
  ShipMonitor/ShipMonitor.cs
  SpeechService/SpeechFX.cs
  Tests/TestBase.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 8. inconvenience / annoyance, on hold

#1428 Fix crashing in AX conflict zones
  EDDI/ChangeLog.md
  SpeechService/SpeechQueue.cs
  Tests/SpeechUnitTests.cs
Labels: 3. crash / lockup

#1422 Fix unknown station model "Ocellus"
  DataDefinitions/Properties/StationModels.Designer.cs
  DataDefinitions/Properties/StationModels.de.resx
  DataDefinitions/Properties/StationModels.es.resx
  DataDefinitions/Properties/StationModels.fr.resx
  DataDefinitions/Properties/StationModels.it.resx
  DataDefinitions/Properties/StationModels.pt-BR.resx
  DataDefinitions/Properties/StationModels.resx
  DataDefinitions/Properties/StationModels.ru.resx
  DataDefinitions/StationModel.cs
  Tests/DataDefinitionTests.cs
Labels: 8. inconvenience / annoyance
