Repository EDCD/EDDI, pull requests merged in 2019-03, with the labels that each got.

#1223 Hotfix/1155 va delayed events v2
  CompanionAppService/CompanionAppService.cs
  EDDI/EDDI.cs
  EDDI/EDDIMonitor.cs
  EDDI/EDDIResponder.cs
  EDDI/MainWindow.xaml.cs
  EDDNResponder/EDDNResponder.cs
  ShipMonitor/ConfigurationWindow.xaml.cs
  SpeechResponder/Script.cs
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/SpeechResponder.cs
  SpeechService/EddiSpeech.cs
  SpeechService/EddiSpeechService.csproj
  SpeechService/SpeechFX.cs
  SpeechService/SpeechQueue.cs
  SpeechService/SpeechService.cs
  Tests/SpeechTests.cs
  Tests/SpeechUnitTests.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 5. priority / painful

#1250 Fix silent test buttons
  EDDI/ChangeLog.md
  SpeechResponder/ConfigurationWindow.xaml.cs
  SpeechResponder/EditScriptWindow.xaml.cs
  SpeechResponder/SpeechResponder.cs
Labels: 6. bug / not up to spec

#1248 Select home & squadron systems from Combo box
  EDDI/EDDI.cs
  EDDI/MainWindow.xaml
  EDDI/MainWindow.xaml.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
  StarMapService/EdsmSystemData.cs
Labels: 8. inconvenience / annoyance

#1251 For speech invoked from VA, return after speech completes
  SpeechResponder/SpeechResponder.cs
  SpeechService/SpeechService.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 8. inconvenience / annoyance

#1252 Fix missing fileheader events
  EDDI/ChangeLog.md
  JournalMonitor/LogMonitor.cs
Labels: 8. inconvenience / annoyance
