Repository EDCD/EDDI, pull requests merged in 2019-10, with the labels that each got.

#1547 Fix a possible null reference exception with the `MaxFuelPerJump` method
  ShipMonitor/ShipMonitor.cs
Labels: 6. bug / not up to spec

#1545 Update definitions to include Rockforth Fertiliser and Advanced Missile Racks
  DataDefinitions/CommodityDefinition.cs
  DataDefinitions/ModuleDefinitions.cs
  DataDefinitions/Properties/Commodities.Designer.cs
  DataDefinitions/Properties/Commodities.resx
  DataDefinitions/Properties/Modules.Designer.cs
  DataDefinitions/Properties/Modules.resx
Labels: 8. inconvenience / annoyance

#1544 Fix NPC combat interdiction formatting error in Inara.
  InaraResponder/InaraResponder.cs
Labels: 6. bug / not up to spec

#1543 Fix 'cadmium' typo in EDDI.vap file
  VoiceAttackResponder/EDDI.vap
Labels: 8. inconvenience / annoyance

#1546 Fix `Exception obtaining profile` errors
  DataDefinitions/CommodityDefinition.cs
  EDDI/MainWindow.xaml.cs
Labels: 6. bug / not up to spec

#1549 Update the EDDN Responder
  EDDNResponder/EDDNResponder.cs
Labels: 10. back end enhancement / change (user unaffected)

#1559 Fix memory leaks when opening and closing EDDI's main window un…
  EDDI/App.xaml.cs
  EDDI/EDDI.cs
  EDDI/MainWindow.xaml.cs
  SpeechResponder/SpeechResponder.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
  VoiceAttackResponder/VoiceAttackResponder.cs
Labels: 6. bug / not up to spec

#1577 Isolate the EDSM Rest client and use a mock for testing
  CrimeMonitor/CrimeMonitor.cs
  DataProviderService/DataProviderService.cs
  DataProviderService/StarSystemSqLiteRepository.cs
  EDDI.sln
  EDDI/StarSystemComboBox.cs
  EDSMResponder/ConfigurationWindow.xaml.cs
  EDSMResponder/EDSMResponder.cs
  MissionMonitor/EddiMissionMonitor.csproj
  MissionMonitor/MissionMonitor.cs
  NavigationService/NavigationService.cs
  SpeechResponder/EddiSpeechResponder.csproj
  SpeechResponder/ScriptResolver.cs
  StarMapService/EddiStarMapService.csproj
  StarMapService/EdsmBodyData.cs
  StarMapService/EdsmFactionData.cs
  StarMapService/EdsmStationData.cs
  StarMapService/EdsmSystemData.cs
  StarMapService/EdsmTrafficData.cs
  StarMapService/IEdsmService.cs
  StarMapService/StarMapService.cs
  Tests/DataProviderTests.cs
  Tests/EdsmDataTests.cs
  Tests/Properties/CapitalSystems.json
  Tests/Properties/Resources.Designer.cs
  Tests/Properties/Resources.resx
  Tests/Properties/Sol.json
  Tests/Properties/SolBodies.json
  Tests/Properties/SolFactions.json
  Tests/Properties/SolStations.json
  Tests/Properties/cubeSystemsAroundSol.json
  Tests/Properties/sphereAroundSol.json
  Tests/Tests.csproj
  Tests/packages.config
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 10. back end enhancement / change (user unaffected)
