Repository EDCD/EDDI, pull requests merged in 2019-12, with the labels that each got.

#1614 Feature/syntax highlighting
  EDDI/ChangeLog.md
  SpeechResponder/ConfigurationWindow.xaml.cs
  SpeechResponder/CopyPersonalityWindow.xaml
  SpeechResponder/Cottle.xshd
  SpeechResponder/CottleHighlightingDefinition.cs
  SpeechResponder/EddiSpeechResponder.csproj
  SpeechResponder/EditScriptWindow.xaml
  SpeechResponder/EditScriptWindow.xaml.cs
  SpeechResponder/Images/Copy.png
  SpeechResponder/Images/Cut.png
  SpeechResponder/Images/Delete line.png
  SpeechResponder/Images/Delete.png
  SpeechResponder/Images/Find.png
  SpeechResponder/Images/Paste.png
  SpeechResponder/Images/Redo.png
  SpeechResponder/Images/Undo.png
  SpeechResponder/Images/WordWrap.png
  SpeechResponder/Properties/Tooltips.Designer.cs
  SpeechResponder/Properties/Tooltips.de.resx
  SpeechResponder/Properties/Tooltips.es.resx
  SpeechResponder/Properties/Tooltips.fr.resx
  SpeechResponder/Properties/Tooltips.hu.resx
  SpeechResponder/Properties/Tooltips.it.resx
  SpeechResponder/Properties/Tooltips.ja.resx
  SpeechResponder/Properties/Tooltips.pt-BR.resx
  SpeechResponder/Properties/Tooltips.resx
  SpeechResponder/Properties/Tooltips.ru.resx
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/ShowDiffWindow.xaml
  SpeechResponder/ShowDiffWindow.xaml.cs
  SpeechResponder/SpeechResponder.cs
  SpeechResponder/ViewScriptWindow.xaml
  SpeechResponder/ViewScriptWindow.xaml.cs
  SpeechResponder/eddi.json
  SpeechResponder/packages.config
  Tests/GeneratorTests.cs
  Utilities/Diff.cs
Labels: 9. enhancement

#1621 Fix bad data bind causing ship monitor to crash
  ShipMonitor/ConfigurationWindow.xaml
Labels: 3. crash / lockup

#1616 Feature/edsmtimeout
  DataProviderService/StarSystemSqLiteRepository.cs
  StarMapService/StarMapService.cs
Labels: 5. painful

#1618 Improve phonetic ship model fallback names
  DataDefinitions/ShipDefinitions.cs
Labels: 8. annoyance

#1620 Apply workaround for Cereproc IPA support
  SpeechService/SpeechService.cs
Labels: 8. annoyance

#1619 Fix `Sagittarius A*` pronunciation in Cereproc voices
  SpeechService/Translations.cs
Labels: 8. annoyance

#1624 Improve backwards compatibility of ship phonetic name
  DataDefinitions/Ship.cs
Labels: 8. annoyance

#1622 Enable nested functions when using Transmit()
  SpeechResponder/ScriptResolver.cs
Labels: 6. not up to spec

#1625 Fix '...Details()' function exceptions when passed empty strings
  DataDefinitions/CommodityDefinition.cs
  SpeechResponder/ScriptResolver.cs
Labels: 6. not up to spec
