Repository EDCD/EDDI, pull requests merged in 2020-12, with the labels that each got.

#2014 Fix an exception found when testing the `Modules stored` event
  JournalMonitor/JournalMonitor.cs
  ShipMonitor/ModulesStoredEvent.cs
  SpeechResponder/eddi.json
Labels: 6. not up to spec

#2016 Fix SSML exception for faction named "Brazilian Armada X"
  SpeechService/SpeechService.cs
Labels: 6. not up to spec

#2017 Fix failing Inara / EDSM sync on closing or stopping
  EddiInaraService/IInaraService.cs
  EddiInaraService/InaraService.cs
  StarMapService/StarMapService.cs
Labels: 6. not up to spec

#2021 Reduce verbosity of `Mission completed` script
  SpeechResponder/eddi.json
Labels: 8. annoyance, cottle

#2022 Fix `Mission accepted` typo and reduce verbosity
  SpeechResponder/eddi.json
Labels: 6. not up to spec, cottle

#2023 Revise the `Mission redirected` script to filter duplicate similar mission redirects
  SpeechResponder/eddi.json
Labels: 8. annoyance, cottle

#2024 Updated the following scripts to default to current star system if context variable `eddi_context_system_name` is not set:
  SpeechResponder/eddi.json
Labels: 7. confusing, cottle

#2027 Document VA implicit variables `$=` and `$-`
  VoiceAttackResponder/VoiceAttackPlugin.cs
  docs/VoiceAttack-Integration.md
Labels: 7. confusing

#2012 Fix `Humanise()` bugged outputs.
  SpeechService/Translations.cs
  Tests/SpeechUnitTests.cs
Labels: 6. not up to spec

#2020 Fix stacked missions not all updating
  DataDefinitions/MissionStatus.cs
  MissionMonitor/MissionMonitor.cs
Labels: 6. not up to spec

#2038 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  docs/issue_template.md
Labels: 9. enhancement

#2040 Don't disable all SSML tags when a user chooses to disable phonetic speech.
  EDDI/MainWindow.xaml
  EDDI/MainWindow.xaml.cs
  EDDI/Properties/MainWindow.Designer.cs
  EDDI/Properties/MainWindow.de.resx
  EDDI/Properties/MainWindow.es.resx
  EDDI/Properties/MainWindow.fr.resx
  EDDI/Properties/MainWindow.hu.resx
  EDDI/Properties/MainWindow.it.resx
  EDDI/Properties/MainWindow.ja.resx
  EDDI/Properties/MainWindow.pt-BR.resx
  EDDI/Properties/MainWindow.resx
  EDDI/Properties/MainWindow.ru.resx
  SpeechResponder/CustomFunctions/Spacialise.cs
  SpeechResponder/ScriptResolverService/ScriptResolver.cs
  SpeechResponder/Variables.md
  SpeechService/SpeechService.cs
  SpeechService/SpeechServiceConfiguration.cs
  Tests/SpeechUnitTests.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
  docs/VoiceAttack-Integration.md
Labels: 7. confusing

#2031 Fix errors with "Mission completed", "Mission expired" and "Signal de…
  SpeechResponder/eddi.fr.json
Labels: 6. not up to spec, cottle

#2044 Add an optional hint string 2nd parameter to the P() function
  SpeechResponder/CustomFunctions/P.cs
  SpeechResponder/Properties/CustomFunctions.Untranslated.Designer.cs
  SpeechResponder/Properties/CustomFunctions.Untranslated.resx
  SpeechResponder/eddi.json
  SpeechService/Translations.cs
  Tests/TranslationTests.cs
Labels: 9. enhancement
