Repository EDCD/EDDI, pull requests merged in 2020-02, with the labels that each got.

#1695 Change all external HTTP URLs to HTTPS where available
  CompanionAppService/CompanionAppService.cs
  GalnetMonitor/Properties/GalnetMonitor.Designer.cs
  GalnetMonitor/Properties/GalnetMonitor.de.resx
  GalnetMonitor/Properties/GalnetMonitor.es.resx
  GalnetMonitor/Properties/GalnetMonitor.fr.resx
  GalnetMonitor/Properties/GalnetMonitor.it.resx
  GalnetMonitor/Properties/GalnetMonitor.pt-BR.resx
  GalnetMonitor/Properties/GalnetMonitor.resx
  SpeechService/SpeechService.cs
  Tests/SpeechTests.cs
  Utilities/Constants.cs
  Utilities/Properties/IPA.Designer.cs
  Utilities/Properties/IPA.de.resx
  Utilities/Properties/IPA.es.resx
  Utilities/Properties/IPA.it.resx
  Utilities/Properties/IPA.ja.resx
  Utilities/Properties/IPA.pt-BR.resx
  Utilities/Properties/IPA.resx
Labels: 1. security

#1678 Fix MaterialDetails() crashing when material is not set
  SpeechResponder/ScriptResolver.cs
Labels: 6. not up to spec

#1679 Fix xml escaping around Cereproc unique ssml tags
  SpeechService/SpeechService.cs
  Tests/SpeechTests.cs
  Tests/SpeechUnitTests.cs
Labels: 9. enhancement

#1692 ICAO for module grades
  ShipMonitor/ModuleRetrievedEvent.cs
  ShipMonitor/ModuleStoredEvent.cs
  SpeechResponder/SpeechResponder.cs
  SpeechResponder/Variables.md
  SpeechResponder/eddi.json
  SpeechService/SpeechFX.cs
  SpeechService/SpeechService.cs
  SpeechService/SpeechServiceConfiguration.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
  docs/VoiceAttack-Integration.md
Labels: 9. enhancement

#1693 Various script tidy ups. Resolves #1656.
  SpeechResponder/eddi.json
Labels: 8. annoyance, cottle

#1700 Ship swapped and hull health
  DataDefinitions/Module.cs
  DataDefinitions/Ship.cs
  ShipMonitor/ShipMonitor.cs
Labels: 7. confusing

#1703 Update `Star scanned` documented properties
  Events/StarScannedEvent.cs
  Tests/JournalMonitorTests.cs
Labels: 9. enhancement

#1702 Speculative fix for database deserialization crash
  DataProviderService/StarSystemSqLiteRepository.cs
Labels: 3. crash / lockup
