Repository EDCD/EDDI, pull requests merged in 2020-05, with the labels that each got.

#1753 Tidy-ups to RouteDetails() documentation.
  SpeechResponder/Help.md
  docs/VoiceAttack-Integration.md
Labels: 8. annoyance

#1760 Fix invalid IPA for the `Electra` star system
  SpeechService/Properties/Phonetics.Designer.cs
  SpeechService/Properties/Phonetics.resx
  Tests/SpeechTests.cs
Labels: 8. annoyance

#1759 Further harden and null protect our core data services.
  DataProviderService/DataProviderService.cs
  DataProviderService/StarSystemSqLiteRepository.cs
  JournalMonitor/JournalMonitor.cs
  StarMapService/EdsmBodyData.cs
  StarMapService/EdsmFactionData.cs
  StarMapService/EdsmStationData.cs
  StarMapService/EdsmSystemData.cs
Labels: 10. work unit (user unaffected)

#1763 More Inara fixes and tidy ups (rebased from #1756)
  EddiInaraService/EddiInaraService.csproj
  EddiInaraService/IInaraService.cs
  EddiInaraService/InaraAPICmdrProfile.cs
  EddiInaraService/InaraAPIEvent.cs
  EddiInaraService/InaraAuthenticationException.cs
  EddiInaraService/InaraConfiguration.cs
  EddiInaraService/InaraErrorException.cs
  EddiInaraService/InaraException.cs
  EddiInaraService/InaraService.cs
  EddiInaraService/InaraTooManyRequestsException.cs
  InaraResponder/ConfigurationWindow.xaml.cs
  InaraResponder/InaraResponder.cs
  Tests/InaraTests.cs
Labels: 5. painful

#1770 Implement a producer-consumer threading model with the Inara Service.
  EddiInaraService/InaraService.cs
Labels: 6. not up to spec

#1777 Implement carrier jump related events for Elite v3.7
  EDDI/EDDI.cs
  Events/CarrierCooldownEvent.cs
  Events/CarrierJumpCancelledEvent.cs
  Events/CarrierJumpEngagedEvent.cs
  Events/CarrierJumpRequestEvent.cs
  Events/CarrierJumpedEvent.cs
  Events/CarrierPadsLockedEvent.cs
  Events/EddiEvents.csproj
  Events/JumpedEvent.cs
  Events/LocationEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
  Tests/JournalMonitorTests.cs
  Utilities/Constants.cs
Labels: 9. enhancement, please test

#1774 Use CAPI server time for CAPI data reported to EDDN.
  CompanionAppService/CompanionAppService.cs
  CompanionAppService/Profile.cs
  EDDI/EDDI.cs
  Events/MarketInformationUpdatedEvent.cs
  Tests/CommanderDataTests.cs
Labels: 6. not up to spec

#1771 Implement a queuing system for journal events sent through the EDSM Responder
  DataProviderService/DataProviderService.cs
  EDSMResponder/ConfigurationWindow.xaml.cs
  EDSMResponder/EDSMResponder.cs
  StarMapService/IEdsmService.cs
  StarMapService/StarMapConfiguration.cs
  StarMapService/StarMapService.cs
  StatusMonitor/StatusMonitor.cs
Labels: 6. not up to spec

#1775 Update `FSDTarget` and `Bounty` events for Elite v3.7
  Events/FSDTargetEvent.cs
  JournalMonitor/JournalMonitor.cs
Labels: 9. enhancement

#1773 Update `Ship repaired` event for Elite v3.7.
  JournalMonitor/JournalMonitor.cs
  ShipMonitor/ShipRepairedEvent.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.ru.json
  Tests/JournalMonitorTests.cs
Labels: 9. enhancement

#1783 Updated data definitions for ED version 3.6
  DataDefinitions/FactionState.cs
  DataDefinitions/Mission.cs
  DataDefinitions/MissionStatus.cs
  DataDefinitions/MissionType.cs
  DataDefinitions/Properties/FactionStates.Designer.cs
  DataDefinitions/Properties/FactionStates.resx
  DataDefinitions/Properties/MissionStatus.Designer.cs
  DataDefinitions/Properties/MissionStatus.resx
  DataDefinitions/Properties/MissionType.Designer.cs
  DataDefinitions/Properties/MissionType.resx
  SpeechResponder/eddi.json
Labels: 10. work unit (user unaffected)

#1778 Documentation for the F() script function
  SpeechResponder/Help.md
Labels: 7. confusing

#1779 New Crowdin translations
  DataDefinitions/Properties/Commodities.de.resx
  DataDefinitions/Properties/Commodities.fr.resx
  DataDefinitions/Properties/Economies.fr.resx
  DataDefinitions/Properties/FactionStates.de.resx
  DataDefinitions/Properties/FactionStates.es.resx
  DataDefinitions/Properties/FactionStates.fr.resx
  DataDefinitions/Properties/FactionStates.hu.resx
  DataDefinitions/Properties/FactionStates.it.resx
  DataDefinitions/Properties/FactionStates.ja.resx
  DataDefinitions/Properties/FactionStates.pt-BR.resx
  DataDefinitions/Properties/FactionStates.ru.resx
  DataDefinitions/Properties/Governments.fr.resx
  DataDefinitions/Properties/MissionStatus.de.resx
  DataDefinitions/Properties/MissionStatus.es.resx
  DataDefinitions/Properties/MissionStatus.fr.resx
  DataDefinitions/Properties/MissionStatus.hu.resx
  DataDefinitions/Properties/MissionStatus.it.resx
  DataDefinitions/Properties/MissionStatus.ja.resx
  DataDefinitions/Properties/MissionStatus.pt-BR.resx
  DataDefinitions/Properties/MissionStatus.ru.resx
  DataDefinitions/Properties/MissionType.de.resx
  DataDefinitions/Properties/MissionType.es.resx
  DataDefinitions/Properties/MissionType.fr.resx
  DataDefinitions/Properties/MissionType.hu.resx
  DataDefinitions/Properties/MissionType.it.resx
  DataDefinitions/Properties/MissionType.ja.resx
  DataDefinitions/Properties/MissionType.pt-BR.resx
  DataDefinitions/Properties/MissionType.ru.resx
  DataDefinitions/Properties/StationService.de.resx
  InaraResponder/Properties/InaraResources.fr.resx
  MissionMonitor/Properties/MissionMonitor.fr.resx
  SpeechResponder/Properties/SpeechResponder.fr.resx
  SpeechService/Properties/Phonetics.fr.resx
Labels: 10. work unit (user unaffected)

#1792 Handle null powerplay data in the `Jumped` event
  Events/JumpedEvent.cs
Labels: 6. not up to spec

#1789 (Partial?) fix for Frontier API not connecting
  EDDI/EDDI.cs
Labels: 5. painful
