Repository EDCD/EDDI, pull requests merged in 2020-01, with the labels that each got.

#1663 Fix member assignment in copy constructors
  DataDefinitions/DestinationSystem.cs
  DataDefinitions/Passenger.cs
Labels: 6. not up to spec

#1665 Spacialise(): Improve handling of complex strings
  SpeechResponder/ScriptResolver.cs
  SpeechService/Translations.cs
Labels: 6. not up to spec

#1668 VoiceAttack Variables: Improve object equality comparison
  Tests/DataDefinitionTests.cs
  Utilities/ExtensionMethods.cs
  Utilities/Utilities.csproj
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 6. not up to spec

#1670 Feature/1661 add hardpoints event to status monitor
  EDDI/ChangeLog.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.ja.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
  StatusMonitor/EddiStatusMonitor.csproj
  StatusMonitor/ShipHardpointsEvent.cs
  StatusMonitor/StatusMonitor.cs
Labels: 9. enhancement

#1671 Improve VoiceAttack shutdown / exit
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 8. annoyance

#1660 StatusMonitor: add FlightAssistEvent
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
  StatusMonitor/EddiStatusMonitor.csproj
  StatusMonitor/FlightAssistEvent.cs
  StatusMonitor/StatusMonitor.cs
Labels: 9. enhancement

#1675 Fix voice effects being applied slightly when voice effects should be zero
  SpeechService/SpeechFX.cs
Labels: 8. annoyance
