Repository EDCD/EDDI, pull requests merged in 2020-06, with the labels that each got.

#1791 Resolve possible divide by zero exception in the Status Monitor
  StatusMonitor/StatusMonitor.cs
Labels: 6. not up to spec

#1801 Fix "Reset" button state for edited responder scripts w/ null default values
  SpeechResponder/EditScriptWindow.xaml.cs
  SpeechResponder/Script.cs
Labels: 8. annoyance

#1802 Add a definition for TargetType `TerroristLeader`
  DataDefinitions/Properties/TargetType.resx
  DataDefinitions/TargetType.cs
Labels: 9. enhancement

#1803 Preserve system visits in case EDSM sync fails.
  DataProviderService/DatabaseStarSystem.cs
  DataProviderService/StarSystemSqLiteRepository.cs
  Tests/DataProviderTests.cs
  Tests/Properties/Resources.Designer.cs
  Tests/Properties/Resources.resx
  Tests/Properties/sqlStarSystem5.json
  Tests/Tests.csproj
Labels: 6. not up to spec

#1794 Support sending fleet carrier jump data to Inara
  InaraResponder/InaraResponder.cs
Labels: 6. not up to spec

#1817 Designate nanomedicines as a rare commodity.
  DataDefinitions/CommodityDefinition.cs
Labels: 10. work unit (user unaffected)

#1818 Do not revise average commodity price for fleet carrier data
  DataDefinitions/CommodityMarketQuote.cs
Labels: 7. confusing

#1820 Fix possible `CarrierJumpRequest` crash
  Events/CarrierJumpRequestEvent.cs
  JournalMonitor/JournalMonitor.cs
  Tests/JournalMonitorTests.cs
  Tests/Properties/edsmSystem.json
Labels: 3. crash / lockup

#1826 Update current station info from the `Docked` even if we're already docked.
  EDDI/EDDI.cs
Labels: 7. confusing

#1825 Reduced filesystem polling when Elite is not active.
  JournalMonitor/LogMonitor.cs
  StatusMonitor/StatusMonitor.cs
  Utilities/Processes.cs
  Utilities/Utilities.csproj
Labels: 10. work unit (user unaffected)

#1829 Speculative fix for CAPI null reference exception
  DataDefinitions/CommodityMarketQuote.cs
Labels: 6. not up to spec

#1831 Prevent IO exceptions
  CargoMonitor/CargoMonitorConfiguration.cs
  CompanionAppService/CommanderConfiguration.cs
  CompanionAppService/CompanionAppCredentials.cs
  CrimeMonitor/CrimeMonitorConfiguration.cs
  EDDI/EDDIConfiguration.cs
  EDDI/EliteConfiguration.cs
  EDDI/MainWindow.xaml.cs
  EDDPMonitor/EddpConfiguration.cs
  EddiInaraService/InaraConfiguration.cs
  GalnetMonitor/GalnetConfiguration.cs
  MaterialMonitor/MaterialMonitorConfiguration.cs
  MissionMonitor/MissionMonitorConfiguration.cs
  ShipMonitor/ShipMonitorConfiguration.cs
  SpeechResponder/Personality.cs
  SpeechResponder/SpeechResponderConfiguration.cs
  SpeechService/SpeechServiceConfiguration.cs
  StarMapService/StarMapConfiguration.cs
  Utilities/Files.cs
  Utilities/LockManager.cs
  Utilities/Utilities.csproj
Labels: 5. painful

#1824 Improvements to phonetics
  CrimeMonitor/CrimeMonitor.cs
  DataDefinitions/Ship.cs
  DataDefinitions/ShipDefinitions.cs
  NavigationService/NavigationService.cs
  ShipMonitor/ShipMonitor.cs
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/Variables.md
  SpeechService/SpeechFX.cs
  SpeechService/Translations.cs
  Tests/NavigationServiceTests.cs
  Tests/ScriptResolverTest.cs
  Tests/SpeechTests.cs
  Tests/SpeechUnitTests.cs
  Tests/TranslationTests.cs
  Tests/VoiceAttackPluginTests.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
Labels: 9. enhancement

#1845 Fix speech config inconsistency
  EDDI/MainWindow.xaml.cs
  SpeechService/SpeechService.cs
  Utilities/Files.cs
Labels: 5. painful

#1841 Handle null or empty ship objects in the Inara Responder
  InaraResponder/InaraResponder.cs
Labels: 6. not up to spec

#1842 Fix CommodityMarketQuote.cs/FromCapiJson() null reference exception
  DataDefinitions/CommodityMarketQuote.cs
  Tests/DataDefinitionTests.cs
Labels: 6. not up to spec

#1840 Fix `TrafficDetails()` null reference exception
  StarMapService/EdsmTrafficData.cs
  Tests/EdsmDataTests.cs
  Utilities/ExtensionMethods.cs
Labels: 6. not up to spec

#1838 Fix possible exception in StarSystem.cs/PreserveBodyData()
  DataDefinitions/StarSystem.cs
Labels: 6. not up to spec

#1839 Fix `Carrier jump engaged` null reference
  EDDI/EDDI.cs
Labels: 6. not up to spec

#1836 Update Cottle version
  SpeechResponder/EddiSpeechResponder.csproj
  SpeechResponder/Help.md
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/SpeechResponder.cs
  SpeechResponder/SpeechResponderHelp.md
  SpeechResponder/packages.config
  Tests/ScriptResolverTest.cs
  Tests/Tests.csproj
  Tests/packages.config
Labels: 10. work unit (user unaffected)

#1823 Update Rollbar
  EDDI/App.xaml.cs
  Tests/TestBase.cs
  Tests/Tests.csproj
  Tests/packages.config
  Utilities/Logging.cs
  Utilities/RollbarPayloadsStore.db
  Utilities/Utilities.csproj
  Utilities/app.config
  Utilities/packages.config
Labels: 10. work unit (user unaffected), needs thought

#1849 Cottle script error handling
  SpeechResponder/EddiSpeechResponder.csproj
  SpeechResponder/EditScriptWindow.xaml.cs
  SpeechResponder/ScriptError.cs
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.ru.json
Labels: 6. not up to spec

#1860 Fix Appveyor ambiguous call
  EDDI/EDDI.cs
Labels: 10. work unit (user unaffected)

#1863 Update failing unit test in `TestCargoMissionScenario()`
  Tests/CargoMonitorTests.cs
Labels: 10. work unit (user unaffected)

#1865 Carrier jump refinements
  EDDI/EDDI.cs
  Events/CarrierCooldownEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.es.json
  SpeechResponder/eddi.fr.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.pt-BR.json
  SpeechResponder/eddi.ru.json
  Utilities/Constants.cs
Labels: 6. not up to spec

#1866 Add a simple splash screen
  EDDI/Eddi.csproj
  EDDI/MainWindow.xaml.cs
Labels: 7. confusing
