Repository EDCD/EDDI, pull requests merged in 2020-11, with the labels that each got.

#1962 Convert body properties `alreadydiscovered` and `alreadymapped` to optional bool.
  DataDefinitions/Body.cs
  Events/BodyMappedEvent.cs
  Events/BodyScannedEvent.cs
  Events/StarScannedEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/Variables.md
  Tests/JournalMonitorTests.cs
Labels: 7. confusing

#1981 Send enqueued events to Inara and EDSM prior to stopping
  EddiInaraService/InaraService.cs
  StarMapService/StarMapService.cs
Labels: 6. not up to spec

#1986 Always load required monitors
  EDDI/EDDI.cs
  EDDI/EDDIMonitor.cs
  EDDI/MainWindow.xaml.cs
  EDDI/PluginSkeleton.xaml
  EDDI/PluginSkeleton.xaml.cs
Labels: 7. confusing

#1987 Fix "Error with Signal detected script"
  DataDefinitions/Properties/SignalSource.Designer.cs
  DataDefinitions/Properties/SignalSource.resx
  DataDefinitions/SignalSource.cs
  DataDefinitions/StarSystem.cs
  DataDefinitions/Station.cs
  EDDI/ChangeLog.md
  EDDI/EDDI.cs
  Events/SignalDetectedEvent.cs
  JournalMonitor/JournalMonitor.cs
  SpeechResponder/Variables.md
  SpeechResponder/eddi.json
  Tests/EddiCoreTests.cs
  Tests/JournalMonitorTests.cs
Labels: 6. not up to spec

#1989 Amend singular/plural grammar in Discovery scan script
  SpeechResponder/eddi.json
Labels: 8. annoyance, cottle
