Repository EDCD/EDDI, pull requests merged in 2020-04, with the labels that each got.

#1706 Prefer PLINQ for parallel processing
  BgsService/BgsFactionData.cs
  Tests/BgsDataTests.cs
Labels: 9. enhancement

#1713 Improve EDDI startup speed
  CompanionAppService/CompanionAppService.cs
  DataProviderService/DatabaseStarSystem.cs
  DataProviderService/EddiDataProviderService.csproj
  DataProviderService/StarSystemCache.cs
  DataProviderService/StarSystemSqLiteRepository.cs
  DataProviderService/packages.config
  EDDI/EDDI.cs
  EddiInaraService/InaraService.cs
Labels: 8. annoyance

#1739 Enhance access to the Script resolver from VoiceAttack, improve documentation
  SpeechResponder/ScriptResolver.cs
  SpeechResponder/SpeechResponder.cs
  Tests/ScriptResolverTest.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
  docs/VoiceAttack-Integration.md
Labels: 9. enhancement

#1737 Update definitions for Elite Dangerous v3.7
  DataDefinitions/CommodityDefinition.cs
  DataDefinitions/Economy.cs
  DataDefinitions/Government.cs
  DataDefinitions/Properties/Commodities.Designer.cs
  DataDefinitions/Properties/Commodities.resx
  DataDefinitions/Properties/Economies.Designer.cs
  DataDefinitions/Properties/Economies.resx
  DataDefinitions/Properties/Governments.Designer.cs
  DataDefinitions/Properties/Governments.resx
  DataDefinitions/Properties/StationModels.Designer.cs
  DataDefinitions/Properties/StationModels.resx
  DataDefinitions/Properties/StationService.Designer.cs
  DataDefinitions/Properties/StationService.resx
  DataDefinitions/StationModel.cs
  DataDefinitions/StationService.cs
  Tests/DataDefinitionTests.cs
Labels: 10. work unit (user unaffected)

#1734 Fix typo in "Clear Route" description text
  MissionMonitor/Properties/MissionMonitor.resx
Labels: 8. annoyance

#1729 Inara Update
  CompanionAppService/CompanionAppAuthenticationException.cs
  CompanionAppService/CompanionAppErrorException.cs
  CompanionAppService/CompanionAppException.cs
  CompanionAppService/CompanionIllegalStateException.cs
  EDDI/EDDI.cs
  EddiInaraService/EddiInaraService.csproj
  EddiInaraService/IInaraService.cs
  EddiInaraService/InaraAuthenticationException.cs
  EddiInaraService/InaraConfiguration.cs
  EddiInaraService/InaraErrorException.cs
  EddiInaraService/InaraException.cs
  EddiInaraService/InaraService.cs
  EddiInaraService/InaraTooManyRequestsException.cs
  InaraResponder/ConfigurationWindow.xaml
  InaraResponder/ConfigurationWindow.xaml.cs
  InaraResponder/EddiInaraResponder.csproj
  InaraResponder/InaraResponder.cs
  InaraResponder/Properties/InaraResources.Designer.cs
  InaraResponder/Properties/InaraResources.resx
  SpeechResponder/ScriptResolver.cs
  Tests/InaraTests.cs
  VoiceAttackResponder/VoiceAttackPlugin.cs
Labels: 9. enhancement

#1728 EDSM credentials
  DataProviderService/DataProviderService.cs
  EDDI/EDDI.cs
  EDSMResponder/EDSMResponder.cs
  StarMapService/IEdsmService.cs
  StarMapService/StarMapService.cs
Labels: 10. work unit (user unaffected)

#1707 PLINQ parallel processing for EDSM data
  StarMapService/EdsmBodyData.cs
  StarMapService/EdsmFactionData.cs
  StarMapService/EdsmStationData.cs
  StarMapService/EdsmSystemData.cs
  Tests/EdsmDataTests.cs
Labels: 9. enhancement

#1727 Update `ship` variables and more efficiently handle ship distance calcs
  DataDefinitions/Ship.cs
  JournalMonitor/JournalMonitor.cs
  ShipMonitor/EddiShipMonitor.csproj
  ShipMonitor/FrontierApi.cs
  ShipMonitor/ShipMonitor.cs
  SpeechResponder/Variables.md
  Tests/ShipTests.cs
  VoiceAttackResponder/VoiceAttackVariables.cs
  docs/VoiceAttack-Integration.md
Labels: 6. not up to spec

#1733 More flexible salutes for the `Message received` script
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
  SpeechResponder/eddi.ru.json
Labels: 9. enhancement

#1738 Fix potentially null faction state objects
  BgsService/BgsFactionData.cs
  DataDefinitions/FactionState.cs
  DataDefinitions/StarSystem.cs
  JournalMonitor/JournalMonitor.cs
Labels: 6. not up to spec

#1741 Support the Elite v3.7 `CarrierJump` event in the EDDN responder
  EDDNResponder/EDDNResponder.cs
Labels: 10. work unit (user unaffected)

#1749 Fix Inara service exception that can occur when the server does not respond
  EddiInaraService/InaraService.cs
Labels: 3. crash / lockup

#1747 Minor null protection around getting factions
  BgsService/BgsFactionData.cs
Labels: 6. not up to spec

#1751 `Fuel check` script: Improve response where a non-primary star is scoopable.
  DataDefinitions/StarSystem.cs
  SpeechResponder/Variables.md
  SpeechResponder/eddi.de.json
  SpeechResponder/eddi.hu.json
  SpeechResponder/eddi.it.json
  SpeechResponder/eddi.json
Labels: 7. confusing
